// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcjkiiwjxzyzelnrduqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjamtpaXdqeHp5emVsbnJkdXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NzI3MjUsImV4cCI6MjA3MjM0ODcyNX0.ZdmF39OFVDRy5KX9qnIARkdoc8hUcZUJV5vL--UWLA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});